<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['id' => '001', 'name' => 'Quận Ba Đình', 'region_id' => '01'],
            ['id' => '002', 'name' => 'Quận Hoàn Kiếm', 'region_id' => '01'],
            ['id' => '003', 'name' => 'Quận Tây Hồ', 'region_id' => '01'],
            ['id' => '004', 'name' => 'Quận Long Biên', 'region_id' => '01'],
            ['id' => '005', 'name' => 'Quận Cầu Giấy', 'region_id' => '01'],
            ['id' => '006', 'name' => 'Quận Đống Đa', 'region_id' => '01'],
            ['id' => '007', 'name' => 'Quận Hai Bà Trưng', 'region_id' => '01'],
            ['id' => '008', 'name' => 'Quận Hoàng Mai', 'region_id' => '01'],
            ['id' => '009', 'name' => 'Quận Thanh Xuân', 'region_id' => '01'],
            ['id' => '016', 'name' => 'Huyện Sóc Sơn', 'region_id' => '01'],
            ['id' => '017', 'name' => 'Huyện Đông Anh', 'region_id' => '01'],
            ['id' => '018', 'name' => 'Huyện Gia Lâm', 'region_id' => '01'],
            ['id' => '019', 'name' => 'Quận Nam Từ Liêm', 'region_id' => '01'],
            ['id' => '020', 'name' => 'Huyện Thanh Trì', 'region_id' => '01'],
            ['id' => '021', 'name' => 'Quận Bắc Từ Liêm', 'region_id' => '01'],
            ['id' => '250', 'name' => 'Huyện Mê Linh', 'region_id' => '01'],
            ['id' => '268', 'name' => 'Quận Hà Đông', 'region_id' => '01'],
            ['id' => '269', 'name' => 'Thị xã Sơn Tây', 'region_id' => '01'],
            ['id' => '271', 'name' => 'Huyện Ba Vì', 'region_id' => '01'],
            ['id' => '272', 'name' => 'Huyện Phúc Thọ', 'region_id' => '01'],
            ['id' => '273', 'name' => 'Huyện Đan Phượng', 'region_id' => '01'],
            ['id' => '274', 'name' => 'Huyện Hoài Đức', 'region_id' => '01'],
            ['id' => '275', 'name' => 'Huyện Quốc Oai', 'region_id' => '01'],
            ['id' => '276', 'name' => 'Huyện Thạch Thất', 'region_id' => '01'],
            ['id' => '277', 'name' => 'Huyện Chương Mỹ', 'region_id' => '01'],
            ['id' => '278', 'name' => 'Huyện Thanh Oai', 'region_id' => '01'],
            ['id' => '279', 'name' => 'Huyện Thường Tín', 'region_id' => '01'],
            ['id' => '280', 'name' => 'Huyện Phú Xuyên', 'region_id' => '01'],
            ['id' => '281', 'name' => 'Huyện Ứng Hòa', 'region_id' => '01'],
            ['id' => '282', 'name' => 'Huyện Mỹ Đức', 'region_id' => '01'],
            ['id' => '024', 'name' => 'Thành phố Hà Giang', 'region_id' => '02'],
            ['id' => '026', 'name' => 'Huyện Đồng Văn', 'region_id' => '02'],
            ['id' => '027', 'name' => 'Huyện Mèo Vạc', 'region_id' => '02'],
            ['id' => '028', 'name' => 'Huyện Yên Minh', 'region_id' => '02'],
            ['id' => '029', 'name' => 'Huyện Quản Bạ', 'region_id' => '02'],
            ['id' => '030', 'name' => 'Huyện Vị Xuyên', 'region_id' => '02'],
            ['id' => '031', 'name' => 'Huyện Bắc Mê', 'region_id' => '02'],
            ['id' => '032', 'name' => 'Huyện Hoàng Su Phì', 'region_id' => '02'],
            ['id' => '033', 'name' => 'Huyện Xín Mần', 'region_id' => '02'],
            ['id' => '034', 'name' => 'Huyện Bắc Quang', 'region_id' => '02'],
            ['id' => '035', 'name' => 'Huyện Quang Bình', 'region_id' => '02'],
            ['id' => '040', 'name' => 'Thành phố Cao Bằng', 'region_id' => '04'],
            ['id' => '042', 'name' => 'Huyện Bảo Lâm', 'region_id' => '04'],
            ['id' => '043', 'name' => 'Huyện Bảo Lạc', 'region_id' => '04'],
            ['id' => '044', 'name' => 'Huyện Thông Nông', 'region_id' => '04'],
            ['id' => '045', 'name' => 'Huyện Hà Quảng', 'region_id' => '04'],
            ['id' => '046', 'name' => 'Huyện Trà Lĩnh', 'region_id' => '04'],
            ['id' => '047', 'name' => 'Huyện Trùng Khánh', 'region_id' => '04'],
            ['id' => '048', 'name' => 'Huyện Hạ Lang', 'region_id' => '04'],
            ['id' => '049', 'name' => 'Huyện Quảng Uyên', 'region_id' => '04'],
            ['id' => '050', 'name' => 'Huyện Phục Hoà', 'region_id' => '04'],
            ['id' => '051', 'name' => 'Huyện Hoà An', 'region_id' => '04'],
            ['id' => '052', 'name' => 'Huyện Nguyên Bình', 'region_id' => '04'],
            ['id' => '053', 'name' => 'Huyện Thạch An', 'region_id' => '04'],
            ['id' => '058', 'name' => 'Thành Phố Bắc Kạn', 'region_id' => '06'],
            ['id' => '060', 'name' => 'Huyện Pác Nặm', 'region_id' => '06'],
            ['id' => '061', 'name' => 'Huyện Ba Bể', 'region_id' => '06'],
            ['id' => '062', 'name' => 'Huyện Ngân Sơn', 'region_id' => '06'],
            ['id' => '063', 'name' => 'Huyện Bạch Thông', 'region_id' => '06'],
            ['id' => '064', 'name' => 'Huyện Chợ Đồn', 'region_id' => '06'],
            ['id' => '065', 'name' => 'Huyện Chợ Mới', 'region_id' => '06'],
            ['id' => '066', 'name' => 'Huyện Na Rì', 'region_id' => '06'],
            ['id' => '070', 'name' => 'Thành phố Tuyên Quang', 'region_id' => '08'],
            ['id' => '071', 'name' => 'Huyện Lâm Bình', 'region_id' => '08'],
            ['id' => '072', 'name' => 'Huyện Na Hang', 'region_id' => '08'],
            ['id' => '073', 'name' => 'Huyện Chiêm Hóa', 'region_id' => '08'],
            ['id' => '074', 'name' => 'Huyện Hàm Yên', 'region_id' => '08'],
            ['id' => '075', 'name' => 'Huyện Yên Sơn', 'region_id' => '08'],
            ['id' => '076', 'name' => 'Huyện Sơn Dương', 'region_id' => '08'],
            ['id' => '080', 'name' => 'Thành phố Lào Cai', 'region_id' => '10'],
            ['id' => '082', 'name' => 'Huyện Bát Xát', 'region_id' => '10'],
            ['id' => '083', 'name' => 'Huyện Mường Khương', 'region_id' => '10'],
            ['id' => '084', 'name' => 'Huyện Si Ma Cai', 'region_id' => '10'],
            ['id' => '085', 'name' => 'Huyện Bắc Hà', 'region_id' => '10'],
            ['id' => '086', 'name' => 'Huyện Bảo Thắng', 'region_id' => '10'],
            ['id' => '087', 'name' => 'Huyện Bảo Yên', 'region_id' => '10'],
            ['id' => '088', 'name' => 'Huyện Sa Pa', 'region_id' => '10'],
            ['id' => '089', 'name' => 'Huyện Văn Bàn', 'region_id' => '10'],
            ['id' => '094', 'name' => 'Thành phố Điện Biên Phủ', 'region_id' => '11'],
            ['id' => '095', 'name' => 'Thị Xã Mường Lay', 'region_id' => '11'],
            ['id' => '096', 'name' => 'Huyện Mường Nhé', 'region_id' => '11'],
            ['id' => '097', 'name' => 'Huyện Mường Chà', 'region_id' => '11'],
            ['id' => '098', 'name' => 'Huyện Tủa Chùa', 'region_id' => '11'],
            ['id' => '099', 'name' => 'Huyện Tuần Giáo', 'region_id' => '11'],
            ['id' => '100', 'name' => 'Huyện Điện Biên', 'region_id' => '11'],
            ['id' => '101', 'name' => 'Huyện Điện Biên Đông', 'region_id' => '11'],
            ['id' => '102', 'name' => 'Huyện Mường Ảng', 'region_id' => '11'],
            ['id' => '103', 'name' => 'Huyện Nậm Pồ', 'region_id' => '11'],
            ['id' => '105', 'name' => 'Thành phố Lai Châu', 'region_id' => '12'],
            ['id' => '106', 'name' => 'Huyện Tam Đường', 'region_id' => '12'],
            ['id' => '107', 'name' => 'Huyện Mường Tè', 'region_id' => '12'],
            ['id' => '108', 'name' => 'Huyện Sìn Hồ', 'region_id' => '12'],
            ['id' => '109', 'name' => 'Huyện Phong Thổ', 'region_id' => '12'],
            ['id' => '110', 'name' => 'Huyện Than Uyên', 'region_id' => '12'],
            ['id' => '111', 'name' => 'Huyện Tân Uyên', 'region_id' => '12'],
            ['id' => '112', 'name' => 'Huyện Nậm Nhùn', 'region_id' => '12'],
            ['id' => '116', 'name' => 'Thành phố Sơn La', 'region_id' => '14'],
            ['id' => '118', 'name' => 'Huyện Quỳnh Nhai', 'region_id' => '14'],
            ['id' => '119', 'name' => 'Huyện Thuận Châu', 'region_id' => '14'],
            ['id' => '120', 'name' => 'Huyện Mường La', 'region_id' => '14'],
            ['id' => '121', 'name' => 'Huyện Bắc Yên', 'region_id' => '14'],
            ['id' => '122', 'name' => 'Huyện Phù Yên', 'region_id' => '14'],
            ['id' => '123', 'name' => 'Huyện Mộc Châu', 'region_id' => '14'],
            ['id' => '124', 'name' => 'Huyện Yên Châu', 'region_id' => '14'],
            ['id' => '125', 'name' => 'Huyện Mai Sơn', 'region_id' => '14'],
            ['id' => '126', 'name' => 'Huyện Sông Mã', 'region_id' => '14'],
            ['id' => '127', 'name' => 'Huyện Sốp Cộp', 'region_id' => '14'],
            ['id' => '128', 'name' => 'Huyện Vân Hồ', 'region_id' => '14'],
            ['id' => '132', 'name' => 'Thành phố Yên Bái', 'region_id' => '15'],
            ['id' => '133', 'name' => 'Thị xã Nghĩa Lộ', 'region_id' => '15'],
            ['id' => '135', 'name' => 'Huyện Lục Yên', 'region_id' => '15'],
            ['id' => '136', 'name' => 'Huyện Văn Yên', 'region_id' => '15'],
            ['id' => '137', 'name' => 'Huyện Mù Căng Chải', 'region_id' => '15'],
            ['id' => '138', 'name' => 'Huyện Trấn Yên', 'region_id' => '15'],
            ['id' => '139', 'name' => 'Huyện Trạm Tấu', 'region_id' => '15'],
            ['id' => '140', 'name' => 'Huyện Văn Chấn', 'region_id' => '15'],
            ['id' => '141', 'name' => 'Huyện Yên Bình', 'region_id' => '15'],
            ['id' => '148', 'name' => 'Thành phố Hòa Bình', 'region_id' => '17'],
            ['id' => '150', 'name' => 'Huyện Đà Bắc', 'region_id' => '17'],
            ['id' => '151', 'name' => 'Huyện Kỳ Sơn', 'region_id' => '17'],
            ['id' => '152', 'name' => 'Huyện Lương Sơn', 'region_id' => '17'],
            ['id' => '153', 'name' => 'Huyện Kim Bôi', 'region_id' => '17'],
            ['id' => '154', 'name' => 'Huyện Cao Phong', 'region_id' => '17'],
            ['id' => '155', 'name' => 'Huyện Tân Lạc', 'region_id' => '17'],
            ['id' => '156', 'name' => 'Huyện Mai Châu', 'region_id' => '17'],
            ['id' => '157', 'name' => 'Huyện Lạc Sơn', 'region_id' => '17'],
            ['id' => '158', 'name' => 'Huyện Yên Thủy', 'region_id' => '17'],
            ['id' => '159', 'name' => 'Huyện Lạc Thủy', 'region_id' => '17'],
            ['id' => '164', 'name' => 'Thành phố Thái Nguyên', 'region_id' => '19'],
            ['id' => '165', 'name' => 'Thành phố Sông Công', 'region_id' => '19'],
            ['id' => '167', 'name' => 'Huyện Định Hóa', 'region_id' => '19'],
            ['id' => '168', 'name' => 'Huyện Phú Lương', 'region_id' => '19'],
            ['id' => '169', 'name' => 'Huyện Đồng Hỷ', 'region_id' => '19'],
            ['id' => '170', 'name' => 'Huyện Võ Nhai', 'region_id' => '19'],
            ['id' => '171', 'name' => 'Huyện Đại Từ', 'region_id' => '19'],
            ['id' => '172', 'name' => 'Thị xã Phổ Yên', 'region_id' => '19'],
            ['id' => '173', 'name' => 'Huyện Phú Bình', 'region_id' => '19'],
            ['id' => '178', 'name' => 'Thành phố Lạng Sơn', 'region_id' => '20'],
            ['id' => '180', 'name' => 'Huyện Tràng Định', 'region_id' => '20'],
            ['id' => '181', 'name' => 'Huyện Bình Gia', 'region_id' => '20'],
            ['id' => '182', 'name' => 'Huyện Văn Lãng', 'region_id' => '20'],
            ['id' => '183', 'name' => 'Huyện Cao Lộc', 'region_id' => '20'],
            ['id' => '184', 'name' => 'Huyện Văn Quan', 'region_id' => '20'],
            ['id' => '185', 'name' => 'Huyện Bắc Sơn', 'region_id' => '20'],
            ['id' => '186', 'name' => 'Huyện Hữu Lũng', 'region_id' => '20'],
            ['id' => '187', 'name' => 'Huyện Chi Lăng', 'region_id' => '20'],
            ['id' => '188', 'name' => 'Huyện Lộc Bình', 'region_id' => '20'],
            ['id' => '189', 'name' => 'Huyện Đình Lập', 'region_id' => '20'],
            ['id' => '193', 'name' => 'Thành phố Hạ Long', 'region_id' => '22'],
            ['id' => '194', 'name' => 'Thành phố Móng Cái', 'region_id' => '22'],
            ['id' => '195', 'name' => 'Thành phố Cẩm Phả', 'region_id' => '22'],
            ['id' => '196', 'name' => 'Thành phố Uông Bí', 'region_id' => '22'],
            ['id' => '198', 'name' => 'Huyện Bình Liêu', 'region_id' => '22'],
            ['id' => '199', 'name' => 'Huyện Tiên Yên', 'region_id' => '22'],
            ['id' => '200', 'name' => 'Huyện Đầm Hà', 'region_id' => '22'],
            ['id' => '201', 'name' => 'Huyện Hải Hà', 'region_id' => '22'],
            ['id' => '202', 'name' => 'Huyện Ba Chẽ', 'region_id' => '22'],
            ['id' => '203', 'name' => 'Huyện Vân Đồn', 'region_id' => '22'],
            ['id' => '204', 'name' => 'Huyện Hoành Bồ', 'region_id' => '22'],
            ['id' => '205', 'name' => 'Thị xã Đông Triều', 'region_id' => '22'],
            ['id' => '206', 'name' => 'Thị xã Quảng Yên', 'region_id' => '22'],
            ['id' => '207', 'name' => 'Huyện Cô Tô', 'region_id' => '22'],
            ['id' => '213', 'name' => 'Thành phố Bắc Giang', 'region_id' => '24'],
            ['id' => '215', 'name' => 'Huyện Yên Thế', 'region_id' => '24'],
            ['id' => '216', 'name' => 'Huyện Tân Yên', 'region_id' => '24'],
            ['id' => '217', 'name' => 'Huyện Lạng Giang', 'region_id' => '24'],
            ['id' => '218', 'name' => 'Huyện Lục Nam', 'region_id' => '24'],
            ['id' => '219', 'name' => 'Huyện Lục Ngạn', 'region_id' => '24'],
            ['id' => '220', 'name' => 'Huyện Sơn Động', 'region_id' => '24'],
            ['id' => '221', 'name' => 'Huyện Yên Dũng', 'region_id' => '24'],
            ['id' => '222', 'name' => 'Huyện Việt Yên', 'region_id' => '24'],
            ['id' => '223', 'name' => 'Huyện Hiệp Hòa', 'region_id' => '24'],
            ['id' => '227', 'name' => 'Thành phố Việt Trì', 'region_id' => '25'],
            ['id' => '228', 'name' => 'Thị xã Phú Thọ', 'region_id' => '25'],
            ['id' => '230', 'name' => 'Huyện Đoan Hùng', 'region_id' => '25'],
            ['id' => '231', 'name' => 'Huyện Hạ Hoà', 'region_id' => '25'],
            ['id' => '232', 'name' => 'Huyện Thanh Ba', 'region_id' => '25'],
            ['id' => '233', 'name' => 'Huyện Phù Ninh', 'region_id' => '25'],
            ['id' => '234', 'name' => 'Huyện Yên Lập', 'region_id' => '25'],
            ['id' => '235', 'name' => 'Huyện Cẩm Khê', 'region_id' => '25'],
            ['id' => '236', 'name' => 'Huyện Tam Nông', 'region_id' => '25'],
            ['id' => '237', 'name' => 'Huyện Lâm Thao', 'region_id' => '25'],
            ['id' => '238', 'name' => 'Huyện Thanh Sơn', 'region_id' => '25'],
            ['id' => '239', 'name' => 'Huyện Thanh Thuỷ', 'region_id' => '25'],
            ['id' => '240', 'name' => 'Huyện Tân Sơn', 'region_id' => '25'],
            ['id' => '243', 'name' => 'Thành phố Vĩnh Yên', 'region_id' => '26'],
            ['id' => '244', 'name' => 'Thành phố Phúc Yên', 'region_id' => '26'],
            ['id' => '246', 'name' => 'Huyện Lập Thạch', 'region_id' => '26'],
            ['id' => '247', 'name' => 'Huyện Tam Dương', 'region_id' => '26'],
            ['id' => '248', 'name' => 'Huyện Tam Đảo', 'region_id' => '26'],
            ['id' => '249', 'name' => 'Huyện Bình Xuyên', 'region_id' => '26'],
            ['id' => '251', 'name' => 'Huyện Yên Lạc', 'region_id' => '26'],
            ['id' => '252', 'name' => 'Huyện Vĩnh Tường', 'region_id' => '26'],
            ['id' => '253', 'name' => 'Huyện Sông Lô', 'region_id' => '26'],
            ['id' => '256', 'name' => 'Thành phố Bắc Ninh', 'region_id' => '27'],
            ['id' => '258', 'name' => 'Huyện Yên Phong', 'region_id' => '27'],
            ['id' => '259', 'name' => 'Huyện Quế Võ', 'region_id' => '27'],
            ['id' => '260', 'name' => 'Huyện Tiên Du', 'region_id' => '27'],
            ['id' => '261', 'name' => 'Thị xã Từ Sơn', 'region_id' => '27'],
            ['id' => '262', 'name' => 'Huyện Thuận Thành', 'region_id' => '27'],
            ['id' => '263', 'name' => 'Huyện Gia Bình', 'region_id' => '27'],
            ['id' => '264', 'name' => 'Huyện Lương Tài', 'region_id' => '27'],
            ['id' => '288', 'name' => 'Thành phố Hải Dương', 'region_id' => '30'],
            ['id' => '290', 'name' => 'Thành phố Chí Linh', 'region_id' => '30'],
            ['id' => '291', 'name' => 'Huyện Nam Sách', 'region_id' => '30'],
            ['id' => '292', 'name' => 'Huyện Kinh Môn', 'region_id' => '30'],
            ['id' => '293', 'name' => 'Huyện Kim Thành', 'region_id' => '30'],
            ['id' => '294', 'name' => 'Huyện Thanh Hà', 'region_id' => '30'],
            ['id' => '295', 'name' => 'Huyện Cẩm Giàng', 'region_id' => '30'],
            ['id' => '296', 'name' => 'Huyện Bình Giang', 'region_id' => '30'],
            ['id' => '297', 'name' => 'Huyện Gia Lộc', 'region_id' => '30'],
            ['id' => '298', 'name' => 'Huyện Tứ Kỳ', 'region_id' => '30'],
            ['id' => '299', 'name' => 'Huyện Ninh Giang', 'region_id' => '30'],
            ['id' => '300', 'name' => 'Huyện Thanh Miện', 'region_id' => '30'],
            ['id' => '303', 'name' => 'Quận Hồng Bàng', 'region_id' => '31'],
            ['id' => '304', 'name' => 'Quận Ngô Quyền', 'region_id' => '31'],
            ['id' => '305', 'name' => 'Quận Lê Chân', 'region_id' => '31'],
            ['id' => '306', 'name' => 'Quận Hải An', 'region_id' => '31'],
            ['id' => '307', 'name' => 'Quận Kiến An', 'region_id' => '31'],
            ['id' => '308', 'name' => 'Quận Đồ Sơn', 'region_id' => '31'],
            ['id' => '309', 'name' => 'Quận Dương Kinh', 'region_id' => '31'],
            ['id' => '311', 'name' => 'Huyện Thuỷ Nguyên', 'region_id' => '31'],
            ['id' => '312', 'name' => 'Huyện An Dương', 'region_id' => '31'],
            ['id' => '313', 'name' => 'Huyện An Lão', 'region_id' => '31'],
            ['id' => '314', 'name' => 'Huyện Kiến Thuỵ', 'region_id' => '31'],
            ['id' => '315', 'name' => 'Huyện Tiên Lãng', 'region_id' => '31'],
            ['id' => '316', 'name' => 'Huyện Vĩnh Bảo', 'region_id' => '31'],
            ['id' => '317', 'name' => 'Huyện Cát Hải', 'region_id' => '31'],
            ['id' => '318', 'name' => 'Huyện Bạch Long Vĩ', 'region_id' => '31'],
            ['id' => '323', 'name' => 'Thành phố Hưng Yên', 'region_id' => '33'],
            ['id' => '325', 'name' => 'Huyện Văn Lâm', 'region_id' => '33'],
            ['id' => '326', 'name' => 'Huyện Văn Giang', 'region_id' => '33'],
            ['id' => '327', 'name' => 'Huyện Yên Mỹ', 'region_id' => '33'],
            ['id' => '328', 'name' => 'Thị xã Mỹ Hào', 'region_id' => '33'],
            ['id' => '329', 'name' => 'Huyện Ân Thi', 'region_id' => '33'],
            ['id' => '330', 'name' => 'Huyện Khoái Châu', 'region_id' => '33'],
            ['id' => '331', 'name' => 'Huyện Kim Động', 'region_id' => '33'],
            ['id' => '332', 'name' => 'Huyện Tiên Lữ', 'region_id' => '33'],
            ['id' => '333', 'name' => 'Huyện Phù Cừ', 'region_id' => '33'],
            ['id' => '336', 'name' => 'Thành phố Thái Bình', 'region_id' => '34'],
            ['id' => '338', 'name' => 'Huyện Quỳnh Phụ', 'region_id' => '34'],
            ['id' => '339', 'name' => 'Huyện Hưng Hà', 'region_id' => '34'],
            ['id' => '340', 'name' => 'Huyện Đông Hưng', 'region_id' => '34'],
            ['id' => '341', 'name' => 'Huyện Thái Thụy', 'region_id' => '34'],
            ['id' => '342', 'name' => 'Huyện Tiền Hải', 'region_id' => '34'],
            ['id' => '343', 'name' => 'Huyện Kiến Xương', 'region_id' => '34'],
            ['id' => '344', 'name' => 'Huyện Vũ Thư', 'region_id' => '34'],
            ['id' => '347', 'name' => 'Thành phố Phủ Lý', 'region_id' => '35'],
            ['id' => '349', 'name' => 'Huyện Duy Tiên', 'region_id' => '35'],
            ['id' => '350', 'name' => 'Huyện Kim Bảng', 'region_id' => '35'],
            ['id' => '351', 'name' => 'Huyện Thanh Liêm', 'region_id' => '35'],
            ['id' => '352', 'name' => 'Huyện Bình Lục', 'region_id' => '35'],
            ['id' => '353', 'name' => 'Huyện Lý Nhân', 'region_id' => '35'],
            ['id' => '356', 'name' => 'Thành phố Nam Định', 'region_id' => '36'],
            ['id' => '358', 'name' => 'Huyện Mỹ Lộc', 'region_id' => '36'],
            ['id' => '359', 'name' => 'Huyện Vụ Bản', 'region_id' => '36'],
            ['id' => '360', 'name' => 'Huyện Ý Yên', 'region_id' => '36'],
            ['id' => '361', 'name' => 'Huyện Nghĩa Hưng', 'region_id' => '36'],
            ['id' => '362', 'name' => 'Huyện Nam Trực', 'region_id' => '36'],
            ['id' => '363', 'name' => 'Huyện Trực Ninh', 'region_id' => '36'],
            ['id' => '364', 'name' => 'Huyện Xuân Trường', 'region_id' => '36'],
            ['id' => '365', 'name' => 'Huyện Giao Thủy', 'region_id' => '36'],
            ['id' => '366', 'name' => 'Huyện Hải Hậu', 'region_id' => '36'],
            ['id' => '369', 'name' => 'Thành phố Ninh Bình', 'region_id' => '37'],
            ['id' => '370', 'name' => 'Thành phố Tam Điệp', 'region_id' => '37'],
            ['id' => '372', 'name' => 'Huyện Nho Quan', 'region_id' => '37'],
            ['id' => '373', 'name' => 'Huyện Gia Viễn', 'region_id' => '37'],
            ['id' => '374', 'name' => 'Huyện Hoa Lư', 'region_id' => '37'],
            ['id' => '375', 'name' => 'Huyện Yên Khánh', 'region_id' => '37'],
            ['id' => '376', 'name' => 'Huyện Kim Sơn', 'region_id' => '37'],
            ['id' => '377', 'name' => 'Huyện Yên Mô', 'region_id' => '37'],
            ['id' => '380', 'name' => 'Thành phố Thanh Hóa', 'region_id' => '38'],
            ['id' => '381', 'name' => 'Thị xã Bỉm Sơn', 'region_id' => '38'],
            ['id' => '382', 'name' => 'Thành phố Sầm Sơn', 'region_id' => '38'],
            ['id' => '384', 'name' => 'Huyện Mường Lát', 'region_id' => '38'],
            ['id' => '385', 'name' => 'Huyện Quan Hóa', 'region_id' => '38'],
            ['id' => '386', 'name' => 'Huyện Bá Thước', 'region_id' => '38'],
            ['id' => '387', 'name' => 'Huyện Quan Sơn', 'region_id' => '38'],
            ['id' => '388', 'name' => 'Huyện Lang Chánh', 'region_id' => '38'],
            ['id' => '389', 'name' => 'Huyện Ngọc Lặc', 'region_id' => '38'],
            ['id' => '390', 'name' => 'Huyện Cẩm Thủy', 'region_id' => '38'],
            ['id' => '391', 'name' => 'Huyện Thạch Thành', 'region_id' => '38'],
            ['id' => '392', 'name' => 'Huyện Hà Trung', 'region_id' => '38'],
            ['id' => '393', 'name' => 'Huyện Vĩnh Lộc', 'region_id' => '38'],
            ['id' => '394', 'name' => 'Huyện Yên Định', 'region_id' => '38'],
            ['id' => '395', 'name' => 'Huyện Thọ Xuân', 'region_id' => '38'],
            ['id' => '396', 'name' => 'Huyện Thường Xuân', 'region_id' => '38'],
            ['id' => '397', 'name' => 'Huyện Triệu Sơn', 'region_id' => '38'],
            ['id' => '398', 'name' => 'Huyện Thiệu Hóa', 'region_id' => '38'],
            ['id' => '399', 'name' => 'Huyện Hoằng Hóa', 'region_id' => '38'],
            ['id' => '400', 'name' => 'Huyện Hậu Lộc', 'region_id' => '38'],
            ['id' => '401', 'name' => 'Huyện Nga Sơn', 'region_id' => '38'],
            ['id' => '402', 'name' => 'Huyện Như Xuân', 'region_id' => '38'],
            ['id' => '403', 'name' => 'Huyện Như Thanh', 'region_id' => '38'],
            ['id' => '404', 'name' => 'Huyện Nông Cống', 'region_id' => '38'],
            ['id' => '405', 'name' => 'Huyện Đông Sơn', 'region_id' => '38'],
            ['id' => '406', 'name' => 'Huyện Quảng Xương', 'region_id' => '38'],
            ['id' => '407', 'name' => 'Huyện Tĩnh Gia', 'region_id' => '38'],
            ['id' => '412', 'name' => 'Thành phố Vinh', 'region_id' => '40'],
            ['id' => '413', 'name' => 'Thị xã Cửa Lò', 'region_id' => '40'],
            ['id' => '414', 'name' => 'Thị xã Thái Hoà', 'region_id' => '40'],
            ['id' => '415', 'name' => 'Huyện Quế Phong', 'region_id' => '40'],
            ['id' => '416', 'name' => 'Huyện Quỳ Châu', 'region_id' => '40'],
            ['id' => '417', 'name' => 'Huyện Kỳ Sơn', 'region_id' => '40'],
            ['id' => '418', 'name' => 'Huyện Tương Dương', 'region_id' => '40'],
            ['id' => '419', 'name' => 'Huyện Nghĩa Đàn', 'region_id' => '40'],
            ['id' => '420', 'name' => 'Huyện Quỳ Hợp', 'region_id' => '40'],
            ['id' => '421', 'name' => 'Huyện Quỳnh Lưu', 'region_id' => '40'],
            ['id' => '422', 'name' => 'Huyện Con Cuông', 'region_id' => '40'],
            ['id' => '423', 'name' => 'Huyện Tân Kỳ', 'region_id' => '40'],
            ['id' => '424', 'name' => 'Huyện Anh Sơn', 'region_id' => '40'],
            ['id' => '425', 'name' => 'Huyện Diễn Châu', 'region_id' => '40'],
            ['id' => '426', 'name' => 'Huyện Yên Thành', 'region_id' => '40'],
            ['id' => '427', 'name' => 'Huyện Đô Lương', 'region_id' => '40'],
            ['id' => '428', 'name' => 'Huyện Thanh Chương', 'region_id' => '40'],
            ['id' => '429', 'name' => 'Huyện Nghi Lộc', 'region_id' => '40'],
            ['id' => '430', 'name' => 'Huyện Nam Đàn', 'region_id' => '40'],
            ['id' => '431', 'name' => 'Huyện Hưng Nguyên', 'region_id' => '40'],
            ['id' => '432', 'name' => 'Thị xã Hoàng Mai', 'region_id' => '40'],
            ['id' => '436', 'name' => 'Thành phố Hà Tĩnh', 'region_id' => '42'],
            ['id' => '437', 'name' => 'Thị xã Hồng Lĩnh', 'region_id' => '42'],
            ['id' => '439', 'name' => 'Huyện Hương Sơn', 'region_id' => '42'],
            ['id' => '440', 'name' => 'Huyện Đức Thọ', 'region_id' => '42'],
            ['id' => '441', 'name' => 'Huyện Vũ Quang', 'region_id' => '42'],
            ['id' => '442', 'name' => 'Huyện Nghi Xuân', 'region_id' => '42'],
            ['id' => '443', 'name' => 'Huyện Can Lộc', 'region_id' => '42'],
            ['id' => '444', 'name' => 'Huyện Hương Khê', 'region_id' => '42'],
            ['id' => '445', 'name' => 'Huyện Thạch Hà', 'region_id' => '42'],
            ['id' => '446', 'name' => 'Huyện Cẩm Xuyên', 'region_id' => '42'],
            ['id' => '447', 'name' => 'Huyện Kỳ Anh', 'region_id' => '42'],
            ['id' => '448', 'name' => 'Huyện Lộc Hà', 'region_id' => '42'],
            ['id' => '449', 'name' => 'Thị xã Kỳ Anh', 'region_id' => '42'],
            ['id' => '450', 'name' => 'Thành Phố Đồng Hới', 'region_id' => '44'],
            ['id' => '452', 'name' => 'Huyện Minh Hóa', 'region_id' => '44'],
            ['id' => '453', 'name' => 'Huyện Tuyên Hóa', 'region_id' => '44'],
            ['id' => '454', 'name' => 'Huyện Quảng Trạch', 'region_id' => '44'],
            ['id' => '455', 'name' => 'Huyện Bố Trạch', 'region_id' => '44'],
            ['id' => '456', 'name' => 'Huyện Quảng Ninh', 'region_id' => '44'],
            ['id' => '457', 'name' => 'Huyện Lệ Thủy', 'region_id' => '44'],
            ['id' => '458', 'name' => 'Thị xã Ba Đồn', 'region_id' => '44'],
            ['id' => '461', 'name' => 'Thành phố Đông Hà', 'region_id' => '45'],
            ['id' => '462', 'name' => 'Thị xã Quảng Trị', 'region_id' => '45'],
            ['id' => '464', 'name' => 'Huyện Vĩnh Linh', 'region_id' => '45'],
            ['id' => '465', 'name' => 'Huyện Hướng Hóa', 'region_id' => '45'],
            ['id' => '466', 'name' => 'Huyện Gio Linh', 'region_id' => '45'],
            ['id' => '467', 'name' => 'Huyện Đa Krông', 'region_id' => '45'],
            ['id' => '468', 'name' => 'Huyện Cam Lộ', 'region_id' => '45'],
            ['id' => '469', 'name' => 'Huyện Triệu Phong', 'region_id' => '45'],
            ['id' => '470', 'name' => 'Huyện Hải Lăng', 'region_id' => '45'],
            ['id' => '471', 'name' => 'Huyện Cồn Cỏ', 'region_id' => '45'],
            ['id' => '474', 'name' => 'Thành phố Huế', 'region_id' => '46'],
            ['id' => '476', 'name' => 'Huyện Phong Điền', 'region_id' => '46'],
            ['id' => '477', 'name' => 'Huyện Quảng Điền', 'region_id' => '46'],
            ['id' => '478', 'name' => 'Huyện Phú Vang', 'region_id' => '46'],
            ['id' => '479', 'name' => 'Thị xã Hương Thủy', 'region_id' => '46'],
            ['id' => '480', 'name' => 'Thị xã Hương Trà', 'region_id' => '46'],
            ['id' => '481', 'name' => 'Huyện A Lưới', 'region_id' => '46'],
            ['id' => '482', 'name' => 'Huyện Phú Lộc', 'region_id' => '46'],
            ['id' => '483', 'name' => 'Huyện Nam Đông', 'region_id' => '46'],
            ['id' => '490', 'name' => 'Quận Liên Chiểu', 'region_id' => '48'],
            ['id' => '491', 'name' => 'Quận Thanh Khê', 'region_id' => '48'],
            ['id' => '492', 'name' => 'Quận Hải Châu', 'region_id' => '48'],
            ['id' => '493', 'name' => 'Quận Sơn Trà', 'region_id' => '48'],
            ['id' => '494', 'name' => 'Quận Ngũ Hành Sơn', 'region_id' => '48'],
            ['id' => '495', 'name' => 'Quận Cẩm Lệ', 'region_id' => '48'],
            ['id' => '497', 'name' => 'Huyện Hòa Vang', 'region_id' => '48'],
            ['id' => '498', 'name' => 'Huyện Hoàng Sa', 'region_id' => '48'],
            ['id' => '502', 'name' => 'Thành phố Tam Kỳ', 'region_id' => '49'],
            ['id' => '503', 'name' => 'Thành phố Hội An', 'region_id' => '49'],
            ['id' => '504', 'name' => 'Huyện Tây Giang', 'region_id' => '49'],
            ['id' => '505', 'name' => 'Huyện Đông Giang', 'region_id' => '49'],
            ['id' => '506', 'name' => 'Huyện Đại Lộc', 'region_id' => '49'],
            ['id' => '507', 'name' => 'Thị xã Điện Bàn', 'region_id' => '49'],
            ['id' => '508', 'name' => 'Huyện Duy Xuyên', 'region_id' => '49'],
            ['id' => '509', 'name' => 'Huyện Quế Sơn', 'region_id' => '49'],
            ['id' => '510', 'name' => 'Huyện Nam Giang', 'region_id' => '49'],
            ['id' => '511', 'name' => 'Huyện Phước Sơn', 'region_id' => '49'],
            ['id' => '512', 'name' => 'Huyện Hiệp Đức', 'region_id' => '49'],
            ['id' => '513', 'name' => 'Huyện Thăng Bình', 'region_id' => '49'],
            ['id' => '514', 'name' => 'Huyện Tiên Phước', 'region_id' => '49'],
            ['id' => '515', 'name' => 'Huyện Bắc Trà My', 'region_id' => '49'],
            ['id' => '516', 'name' => 'Huyện Nam Trà My', 'region_id' => '49'],
            ['id' => '517', 'name' => 'Huyện Núi Thành', 'region_id' => '49'],
            ['id' => '518', 'name' => 'Huyện Phú Ninh', 'region_id' => '49'],
            ['id' => '519', 'name' => 'Huyện Nông Sơn', 'region_id' => '49'],
            ['id' => '522', 'name' => 'Thành phố Quảng Ngãi', 'region_id' => '51'],
            ['id' => '524', 'name' => 'Huyện Bình Sơn', 'region_id' => '51'],
            ['id' => '525', 'name' => 'Huyện Trà Bồng', 'region_id' => '51'],
            ['id' => '526', 'name' => 'Huyện Tây Trà', 'region_id' => '51'],
            ['id' => '527', 'name' => 'Huyện Sơn Tịnh', 'region_id' => '51'],
            ['id' => '528', 'name' => 'Huyện Tư Nghĩa', 'region_id' => '51'],
            ['id' => '529', 'name' => 'Huyện Sơn Hà', 'region_id' => '51'],
            ['id' => '530', 'name' => 'Huyện Sơn Tây', 'region_id' => '51'],
            ['id' => '531', 'name' => 'Huyện Minh Long', 'region_id' => '51'],
            ['id' => '532', 'name' => 'Huyện Nghĩa Hành', 'region_id' => '51'],
            ['id' => '533', 'name' => 'Huyện Mộ Đức', 'region_id' => '51'],
            ['id' => '534', 'name' => 'Huyện Đức Phổ', 'region_id' => '51'],
            ['id' => '535', 'name' => 'Huyện Ba Tơ', 'region_id' => '51'],
            ['id' => '536', 'name' => 'Huyện Lý Sơn', 'region_id' => '51'],
            ['id' => '540', 'name' => 'Thành phố Qui Nhơn', 'region_id' => '52'],
            ['id' => '542', 'name' => 'Huyện An Lão', 'region_id' => '52'],
            ['id' => '543', 'name' => 'Huyện Hoài Nhơn', 'region_id' => '52'],
            ['id' => '544', 'name' => 'Huyện Hoài Ân', 'region_id' => '52'],
            ['id' => '545', 'name' => 'Huyện Phù Mỹ', 'region_id' => '52'],
            ['id' => '546', 'name' => 'Huyện Vĩnh Thạnh', 'region_id' => '52'],
            ['id' => '547', 'name' => 'Huyện Tây Sơn', 'region_id' => '52'],
            ['id' => '548', 'name' => 'Huyện Phù Cát', 'region_id' => '52'],
            ['id' => '549', 'name' => 'Thị xã An Nhơn', 'region_id' => '52'],
            ['id' => '550', 'name' => 'Huyện Tuy Phước', 'region_id' => '52'],
            ['id' => '551', 'name' => 'Huyện Vân Canh', 'region_id' => '52'],
            ['id' => '555', 'name' => 'Thành phố Tuy Hoà', 'region_id' => '54'],
            ['id' => '557', 'name' => 'Thị xã Sông Cầu', 'region_id' => '54'],
            ['id' => '558', 'name' => 'Huyện Đồng Xuân', 'region_id' => '54'],
            ['id' => '559', 'name' => 'Huyện Tuy An', 'region_id' => '54'],
            ['id' => '560', 'name' => 'Huyện Sơn Hòa', 'region_id' => '54'],
            ['id' => '561', 'name' => 'Huyện Sông Hinh', 'region_id' => '54'],
            ['id' => '562', 'name' => 'Huyện Tây Hoà', 'region_id' => '54'],
            ['id' => '563', 'name' => 'Huyện Phú Hoà', 'region_id' => '54'],
            ['id' => '564', 'name' => 'Huyện Đông Hòa', 'region_id' => '54'],
            ['id' => '568', 'name' => 'Thành phố Nha Trang', 'region_id' => '56'],
            ['id' => '569', 'name' => 'Thành phố Cam Ranh', 'region_id' => '56'],
            ['id' => '570', 'name' => 'Huyện Cam Lâm', 'region_id' => '56'],
            ['id' => '571', 'name' => 'Huyện Vạn Ninh', 'region_id' => '56'],
            ['id' => '572', 'name' => 'Thị xã Ninh Hòa', 'region_id' => '56'],
            ['id' => '573', 'name' => 'Huyện Khánh Vĩnh', 'region_id' => '56'],
            ['id' => '574', 'name' => 'Huyện Diên Khánh', 'region_id' => '56'],
            ['id' => '575', 'name' => 'Huyện Khánh Sơn', 'region_id' => '56'],
            ['id' => '576', 'name' => 'Huyện Trường Sa', 'region_id' => '56'],
            ['id' => '582', 'name' => 'Thành phố Phan Rang-Tháp Chàm', 'region_id' => '58'],
            ['id' => '584', 'name' => 'Huyện Bác Ái', 'region_id' => '58'],
            ['id' => '585', 'name' => 'Huyện Ninh Sơn', 'region_id' => '58'],
            ['id' => '586', 'name' => 'Huyện Ninh Hải', 'region_id' => '58'],
            ['id' => '587', 'name' => 'Huyện Ninh Phước', 'region_id' => '58'],
            ['id' => '588', 'name' => 'Huyện Thuận Bắc', 'region_id' => '58'],
            ['id' => '589', 'name' => 'Huyện Thuận Nam', 'region_id' => '58'],
            ['id' => '593', 'name' => 'Thành phố Phan Thiết', 'region_id' => '60'],
            ['id' => '594', 'name' => 'Thị xã La Gi', 'region_id' => '60'],
            ['id' => '595', 'name' => 'Huyện Tuy Phong', 'region_id' => '60'],
            ['id' => '596', 'name' => 'Huyện Bắc Bình', 'region_id' => '60'],
            ['id' => '597', 'name' => 'Huyện Hàm Thuận Bắc', 'region_id' => '60'],
            ['id' => '598', 'name' => 'Huyện Hàm Thuận Nam', 'region_id' => '60'],
            ['id' => '599', 'name' => 'Huyện Tánh Linh', 'region_id' => '60'],
            ['id' => '600', 'name' => 'Huyện Đức Linh', 'region_id' => '60'],
            ['id' => '601', 'name' => 'Huyện Hàm Tân', 'region_id' => '60'],
            ['id' => '602', 'name' => 'Huyện Phú Quí', 'region_id' => '60'],
            ['id' => '608', 'name' => 'Thành phố Kon Tum', 'region_id' => '62'],
            ['id' => '610', 'name' => 'Huyện Đắk Glei', 'region_id' => '62'],
            ['id' => '611', 'name' => 'Huyện Ngọc Hồi', 'region_id' => '62'],
            ['id' => '612', 'name' => 'Huyện Đắk Tô', 'region_id' => '62'],
            ['id' => '613', 'name' => 'Huyện Kon Plông', 'region_id' => '62'],
            ['id' => '614', 'name' => 'Huyện Kon Rẫy', 'region_id' => '62'],
            ['id' => '615', 'name' => 'Huyện Đắk Hà', 'region_id' => '62'],
            ['id' => '616', 'name' => 'Huyện Sa Thầy', 'region_id' => '62'],
            ['id' => '617', 'name' => 'Huyện Tu Mơ Rông', 'region_id' => '62'],
            ['id' => '618', 'name' => 'Huyện Ia H\' Drai', 'region_id' => '62'],
            ['id' => '622', 'name' => 'Thành phố Pleiku', 'region_id' => '64'],
            ['id' => '623', 'name' => 'Thị xã An Khê', 'region_id' => '64'],
            ['id' => '624', 'name' => 'Thị xã Ayun Pa', 'region_id' => '64'],
            ['id' => '625', 'name' => 'Huyện KBang', 'region_id' => '64'],
            ['id' => '626', 'name' => 'Huyện Đăk Đoa', 'region_id' => '64'],
            ['id' => '627', 'name' => 'Huyện Chư Păh', 'region_id' => '64'],
            ['id' => '628', 'name' => 'Huyện Ia Grai', 'region_id' => '64'],
            ['id' => '629', 'name' => 'Huyện Mang Yang', 'region_id' => '64'],
            ['id' => '630', 'name' => 'Huyện Kông Chro', 'region_id' => '64'],
            ['id' => '631', 'name' => 'Huyện Đức Cơ', 'region_id' => '64'],
            ['id' => '632', 'name' => 'Huyện Chư Prông', 'region_id' => '64'],
            ['id' => '633', 'name' => 'Huyện Chư Sê', 'region_id' => '64'],
            ['id' => '634', 'name' => 'Huyện Đăk Pơ', 'region_id' => '64'],
            ['id' => '635', 'name' => 'Huyện Ia Pa', 'region_id' => '64'],
            ['id' => '637', 'name' => 'Huyện Krông Pa', 'region_id' => '64'],
            ['id' => '638', 'name' => 'Huyện Phú Thiện', 'region_id' => '64'],
            ['id' => '639', 'name' => 'Huyện Chư Pưh', 'region_id' => '64'],
            ['id' => '643', 'name' => 'Thành phố Buôn Ma Thuột', 'region_id' => '66'],
            ['id' => '644', 'name' => 'Thị Xã Buôn Hồ', 'region_id' => '66'],
            ['id' => '645', 'name' => 'Huyện Ea H\'leo', 'region_id' => '66'],
            ['id' => '646', 'name' => 'Huyện Ea Súp', 'region_id' => '66'],
            ['id' => '647', 'name' => 'Huyện Buôn Đôn', 'region_id' => '66'],
            ['id' => '648', 'name' => 'Huyện Cư M\'gar', 'region_id' => '66'],
            ['id' => '649', 'name' => 'Huyện Krông Búk', 'region_id' => '66'],
            ['id' => '650', 'name' => 'Huyện Krông Năng', 'region_id' => '66'],
            ['id' => '651', 'name' => 'Huyện Ea Kar', 'region_id' => '66'],
            ['id' => '652', 'name' => 'Huyện M\'Đrắk', 'region_id' => '66'],
            ['id' => '653', 'name' => 'Huyện Krông Bông', 'region_id' => '66'],
            ['id' => '654', 'name' => 'Huyện Krông Pắc', 'region_id' => '66'],
            ['id' => '655', 'name' => 'Huyện Krông A Na', 'region_id' => '66'],
            ['id' => '656', 'name' => 'Huyện Lắk', 'region_id' => '66'],
            ['id' => '657', 'name' => 'Huyện Cư Kuin', 'region_id' => '66'],
            ['id' => '660', 'name' => 'Thị xã Gia Nghĩa', 'region_id' => '67'],
            ['id' => '661', 'name' => 'Huyện Đăk Glong', 'region_id' => '67'],
            ['id' => '662', 'name' => 'Huyện Cư Jút', 'region_id' => '67'],
            ['id' => '663', 'name' => 'Huyện Đắk Mil', 'region_id' => '67'],
            ['id' => '664', 'name' => 'Huyện Krông Nô', 'region_id' => '67'],
            ['id' => '665', 'name' => 'Huyện Đắk Song', 'region_id' => '67'],
            ['id' => '666', 'name' => 'Huyện Đắk R\'Lấp', 'region_id' => '67'],
            ['id' => '667', 'name' => 'Huyện Tuy Đức', 'region_id' => '67'],
            ['id' => '672', 'name' => 'Thành phố Đà Lạt', 'region_id' => '68'],
            ['id' => '673', 'name' => 'Thành phố Bảo Lộc', 'region_id' => '68'],
            ['id' => '674', 'name' => 'Huyện Đam Rông', 'region_id' => '68'],
            ['id' => '675', 'name' => 'Huyện Lạc Dương', 'region_id' => '68'],
            ['id' => '676', 'name' => 'Huyện Lâm Hà', 'region_id' => '68'],
            ['id' => '677', 'name' => 'Huyện Đơn Dương', 'region_id' => '68'],
            ['id' => '678', 'name' => 'Huyện Đức Trọng', 'region_id' => '68'],
            ['id' => '679', 'name' => 'Huyện Di Linh', 'region_id' => '68'],
            ['id' => '680', 'name' => 'Huyện Bảo Lâm', 'region_id' => '68'],
            ['id' => '681', 'name' => 'Huyện Đạ Huoai', 'region_id' => '68'],
            ['id' => '682', 'name' => 'Huyện Đạ Tẻh', 'region_id' => '68'],
            ['id' => '683', 'name' => 'Huyện Cát Tiên', 'region_id' => '68'],
            ['id' => '688', 'name' => 'Thị xã Phước Long', 'region_id' => '70'],
            ['id' => '689', 'name' => 'Thành phố Đồng Xoài', 'region_id' => '70'],
            ['id' => '690', 'name' => 'Thị xã Bình Long', 'region_id' => '70'],
            ['id' => '691', 'name' => 'Huyện Bù Gia Mập', 'region_id' => '70'],
            ['id' => '692', 'name' => 'Huyện Lộc Ninh', 'region_id' => '70'],
            ['id' => '693', 'name' => 'Huyện Bù Đốp', 'region_id' => '70'],
            ['id' => '694', 'name' => 'Huyện Hớn Quản', 'region_id' => '70'],
            ['id' => '695', 'name' => 'Huyện Đồng Phú', 'region_id' => '70'],
            ['id' => '696', 'name' => 'Huyện Bù Đăng', 'region_id' => '70'],
            ['id' => '697', 'name' => 'Huyện Chơn Thành', 'region_id' => '70'],
            ['id' => '698', 'name' => 'Huyện Phú Riềng', 'region_id' => '70'],
            ['id' => '703', 'name' => 'Thành phố Tây Ninh', 'region_id' => '72'],
            ['id' => '705', 'name' => 'Huyện Tân Biên', 'region_id' => '72'],
            ['id' => '706', 'name' => 'Huyện Tân Châu', 'region_id' => '72'],
            ['id' => '707', 'name' => 'Huyện Dương Minh Châu', 'region_id' => '72'],
            ['id' => '708', 'name' => 'Huyện Châu Thành', 'region_id' => '72'],
            ['id' => '709', 'name' => 'Huyện Hòa Thành', 'region_id' => '72'],
            ['id' => '710', 'name' => 'Huyện Gò Dầu', 'region_id' => '72'],
            ['id' => '711', 'name' => 'Huyện Bến Cầu', 'region_id' => '72'],
            ['id' => '712', 'name' => 'Huyện Trảng Bàng', 'region_id' => '72'],
            ['id' => '718', 'name' => 'Thành phố Thủ Dầu Một', 'region_id' => '74'],
            ['id' => '719', 'name' => 'Huyện Bàu Bàng', 'region_id' => '74'],
            ['id' => '720', 'name' => 'Huyện Dầu Tiếng', 'region_id' => '74'],
            ['id' => '721', 'name' => 'Thị xã Bến Cát', 'region_id' => '74'],
            ['id' => '722', 'name' => 'Huyện Phú Giáo', 'region_id' => '74'],
            ['id' => '723', 'name' => 'Thị xã Tân Uyên', 'region_id' => '74'],
            ['id' => '724', 'name' => 'Thị xã Dĩ An', 'region_id' => '74'],
            ['id' => '725', 'name' => 'Thị xã Thuận An', 'region_id' => '74'],
            ['id' => '726', 'name' => 'Huyện Bắc Tân Uyên', 'region_id' => '74'],
            ['id' => '731', 'name' => 'Thành phố Biên Hòa', 'region_id' => '75'],
            ['id' => '732', 'name' => 'Thành phố Long Khánh', 'region_id' => '75'],
            ['id' => '734', 'name' => 'Huyện Tân Phú', 'region_id' => '75'],
            ['id' => '735', 'name' => 'Huyện Vĩnh Cửu', 'region_id' => '75'],
            ['id' => '736', 'name' => 'Huyện Định Quán', 'region_id' => '75'],
            ['id' => '737', 'name' => 'Huyện Trảng Bom', 'region_id' => '75'],
            ['id' => '738', 'name' => 'Huyện Thống Nhất', 'region_id' => '75'],
            ['id' => '739', 'name' => 'Huyện Cẩm Mỹ', 'region_id' => '75'],
            ['id' => '740', 'name' => 'Huyện Long Thành', 'region_id' => '75'],
            ['id' => '741', 'name' => 'Huyện Xuân Lộc', 'region_id' => '75'],
            ['id' => '742', 'name' => 'Huyện Nhơn Trạch', 'region_id' => '75'],
            ['id' => '747', 'name' => 'Thành phố Vũng Tàu', 'region_id' => '77'],
            ['id' => '748', 'name' => 'Thành phố Bà Rịa', 'region_id' => '77'],
            ['id' => '750', 'name' => 'Huyện Châu Đức', 'region_id' => '77'],
            ['id' => '751', 'name' => 'Huyện Xuyên Mộc', 'region_id' => '77'],
            ['id' => '752', 'name' => 'Huyện Long Điền', 'region_id' => '77'],
            ['id' => '753', 'name' => 'Huyện Đất Đỏ', 'region_id' => '77'],
            ['id' => '754', 'name' => 'Thị xã Phú Mỹ', 'region_id' => '77'],
            ['id' => '755', 'name' => 'Huyện Côn Đảo', 'region_id' => '77'],
            ['id' => '760', 'name' => 'Quận 1', 'region_id' => '79'],
            ['id' => '761', 'name' => 'Quận 12', 'region_id' => '79'],
            ['id' => '762', 'name' => 'Quận Thủ Đức', 'region_id' => '79'],
            ['id' => '763', 'name' => 'Quận 9', 'region_id' => '79'],
            ['id' => '764', 'name' => 'Quận Gò Vấp', 'region_id' => '79'],
            ['id' => '765', 'name' => 'Quận Bình Thạnh', 'region_id' => '79'],
            ['id' => '766', 'name' => 'Quận Tân Bình', 'region_id' => '79'],
            ['id' => '767', 'name' => 'Quận Tân Phú', 'region_id' => '79'],
            ['id' => '768', 'name' => 'Quận Phú Nhuận', 'region_id' => '79'],
            ['id' => '769', 'name' => 'Quận 2', 'region_id' => '79'],
            ['id' => '770', 'name' => 'Quận 3', 'region_id' => '79'],
            ['id' => '771', 'name' => 'Quận 10', 'region_id' => '79'],
            ['id' => '772', 'name' => 'Quận 11', 'region_id' => '79'],
            ['id' => '773', 'name' => 'Quận 4', 'region_id' => '79'],
            ['id' => '774', 'name' => 'Quận 5', 'region_id' => '79'],
            ['id' => '775', 'name' => 'Quận 6', 'region_id' => '79'],
            ['id' => '776', 'name' => 'Quận 8', 'region_id' => '79'],
            ['id' => '777', 'name' => 'Quận Bình Tân', 'region_id' => '79'],
            ['id' => '778', 'name' => 'Quận 7', 'region_id' => '79'],
            ['id' => '783', 'name' => 'Huyện Củ Chi', 'region_id' => '79'],
            ['id' => '784', 'name' => 'Huyện Hóc Môn', 'region_id' => '79'],
            ['id' => '785', 'name' => 'Huyện Bình Chánh', 'region_id' => '79'],
            ['id' => '786', 'name' => 'Huyện Nhà Bè', 'region_id' => '79'],
            ['id' => '787', 'name' => 'Huyện Cần Giờ', 'region_id' => '79'],
            ['id' => '794', 'name' => 'Thành phố Tân An', 'region_id' => '80'],
            ['id' => '795', 'name' => 'Thị xã Kiến Tường', 'region_id' => '80'],
            ['id' => '796', 'name' => 'Huyện Tân Hưng', 'region_id' => '80'],
            ['id' => '797', 'name' => 'Huyện Vĩnh Hưng', 'region_id' => '80'],
            ['id' => '798', 'name' => 'Huyện Mộc Hóa', 'region_id' => '80'],
            ['id' => '799', 'name' => 'Huyện Tân Thạnh', 'region_id' => '80'],
            ['id' => '800', 'name' => 'Huyện Thạnh Hóa', 'region_id' => '80'],
            ['id' => '801', 'name' => 'Huyện Đức Huệ', 'region_id' => '80'],
            ['id' => '802', 'name' => 'Huyện Đức Hòa', 'region_id' => '80'],
            ['id' => '803', 'name' => 'Huyện Bến Lức', 'region_id' => '80'],
            ['id' => '804', 'name' => 'Huyện Thủ Thừa', 'region_id' => '80'],
            ['id' => '805', 'name' => 'Huyện Tân Trụ', 'region_id' => '80'],
            ['id' => '806', 'name' => 'Huyện Cần Đước', 'region_id' => '80'],
            ['id' => '807', 'name' => 'Huyện Cần Giuộc', 'region_id' => '80'],
            ['id' => '808', 'name' => 'Huyện Châu Thành', 'region_id' => '80'],
            ['id' => '815', 'name' => 'Thành phố Mỹ Tho', 'region_id' => '82'],
            ['id' => '816', 'name' => 'Thị xã Gò Công', 'region_id' => '82'],
            ['id' => '817', 'name' => 'Thị xã Cai Lậy', 'region_id' => '82'],
            ['id' => '818', 'name' => 'Huyện Tân Phước', 'region_id' => '82'],
            ['id' => '819', 'name' => 'Huyện Cái Bè', 'region_id' => '82'],
            ['id' => '820', 'name' => 'Huyện Cai Lậy', 'region_id' => '82'],
            ['id' => '821', 'name' => 'Huyện Châu Thành', 'region_id' => '82'],
            ['id' => '822', 'name' => 'Huyện Chợ Gạo', 'region_id' => '82'],
            ['id' => '823', 'name' => 'Huyện Gò Công Tây', 'region_id' => '82'],
            ['id' => '824', 'name' => 'Huyện Gò Công Đông', 'region_id' => '82'],
            ['id' => '825', 'name' => 'Huyện Tân Phú Đông', 'region_id' => '82'],
            ['id' => '829', 'name' => 'Thành phố Bến Tre', 'region_id' => '83'],
            ['id' => '831', 'name' => 'Huyện Châu Thành', 'region_id' => '83'],
            ['id' => '832', 'name' => 'Huyện Chợ Lách', 'region_id' => '83'],
            ['id' => '833', 'name' => 'Huyện Mỏ Cày Nam', 'region_id' => '83'],
            ['id' => '834', 'name' => 'Huyện Giồng Trôm', 'region_id' => '83'],
            ['id' => '835', 'name' => 'Huyện Bình Đại', 'region_id' => '83'],
            ['id' => '836', 'name' => 'Huyện Ba Tri', 'region_id' => '83'],
            ['id' => '837', 'name' => 'Huyện Thạnh Phú', 'region_id' => '83'],
            ['id' => '838', 'name' => 'Huyện Mỏ Cày Bắc', 'region_id' => '83'],
            ['id' => '842', 'name' => 'Thành phố Trà Vinh', 'region_id' => '84'],
            ['id' => '844', 'name' => 'Huyện Càng Long', 'region_id' => '84'],
            ['id' => '845', 'name' => 'Huyện Cầu Kè', 'region_id' => '84'],
            ['id' => '846', 'name' => 'Huyện Tiểu Cần', 'region_id' => '84'],
            ['id' => '847', 'name' => 'Huyện Châu Thành', 'region_id' => '84'],
            ['id' => '848', 'name' => 'Huyện Cầu Ngang', 'region_id' => '84'],
            ['id' => '849', 'name' => 'Huyện Trà Cú', 'region_id' => '84'],
            ['id' => '850', 'name' => 'Huyện Duyên Hải', 'region_id' => '84'],
            ['id' => '851', 'name' => 'Thị xã Duyên Hải', 'region_id' => '84'],
            ['id' => '855', 'name' => 'Thành phố Vĩnh Long', 'region_id' => '86'],
            ['id' => '857', 'name' => 'Huyện Long Hồ', 'region_id' => '86'],
            ['id' => '858', 'name' => 'Huyện Mang Thít', 'region_id' => '86'],
            ['id' => '859', 'name' => 'Huyện  Vũng Liêm', 'region_id' => '86'],
            ['id' => '860', 'name' => 'Huyện Tam Bình', 'region_id' => '86'],
            ['id' => '861', 'name' => 'Thị xã Bình Minh', 'region_id' => '86'],
            ['id' => '862', 'name' => 'Huyện Trà Ôn', 'region_id' => '86'],
            ['id' => '863', 'name' => 'Huyện Bình Tân', 'region_id' => '86'],
            ['id' => '866', 'name' => 'Thành phố Cao Lãnh', 'region_id' => '87'],
            ['id' => '867', 'name' => 'Thành phố Sa Đéc', 'region_id' => '87'],
            ['id' => '868', 'name' => 'Thị xã Hồng Ngự', 'region_id' => '87'],
            ['id' => '869', 'name' => 'Huyện Tân Hồng', 'region_id' => '87'],
            ['id' => '870', 'name' => 'Huyện Hồng Ngự', 'region_id' => '87'],
            ['id' => '871', 'name' => 'Huyện Tam Nông', 'region_id' => '87'],
            ['id' => '872', 'name' => 'Huyện Tháp Mười', 'region_id' => '87'],
            ['id' => '873', 'name' => 'Huyện Cao Lãnh', 'region_id' => '87'],
            ['id' => '874', 'name' => 'Huyện Thanh Bình', 'region_id' => '87'],
            ['id' => '875', 'name' => 'Huyện Lấp Vò', 'region_id' => '87'],
            ['id' => '876', 'name' => 'Huyện Lai Vung', 'region_id' => '87'],
            ['id' => '877', 'name' => 'Huyện Châu Thành', 'region_id' => '87'],
            ['id' => '883', 'name' => 'Thành phố Long Xuyên', 'region_id' => '89'],
            ['id' => '884', 'name' => 'Thành phố Châu Đốc', 'region_id' => '89'],
            ['id' => '886', 'name' => 'Huyện An Phú', 'region_id' => '89'],
            ['id' => '887', 'name' => 'Thị xã Tân Châu', 'region_id' => '89'],
            ['id' => '888', 'name' => 'Huyện Phú Tân', 'region_id' => '89'],
            ['id' => '889', 'name' => 'Huyện Châu Phú', 'region_id' => '89'],
            ['id' => '890', 'name' => 'Huyện Tịnh Biên', 'region_id' => '89'],
            ['id' => '891', 'name' => 'Huyện Tri Tôn', 'region_id' => '89'],
            ['id' => '892', 'name' => 'Huyện Châu Thành', 'region_id' => '89'],
            ['id' => '893', 'name' => 'Huyện Chợ Mới', 'region_id' => '89'],
            ['id' => '894', 'name' => 'Huyện Thoại Sơn', 'region_id' => '89'],
            ['id' => '899', 'name' => 'Thành phố Rạch Giá', 'region_id' => '91'],
            ['id' => '900', 'name' => 'Thành phố Hà Tiên', 'region_id' => '91'],
            ['id' => '902', 'name' => 'Huyện Kiên Lương', 'region_id' => '91'],
            ['id' => '903', 'name' => 'Huyện Hòn Đất', 'region_id' => '91'],
            ['id' => '904', 'name' => 'Huyện Tân Hiệp', 'region_id' => '91'],
            ['id' => '905', 'name' => 'Huyện Châu Thành', 'region_id' => '91'],
            ['id' => '906', 'name' => 'Huyện Giồng Riềng', 'region_id' => '91'],
            ['id' => '907', 'name' => 'Huyện Gò Quao', 'region_id' => '91'],
            ['id' => '908', 'name' => 'Huyện An Biên', 'region_id' => '91'],
            ['id' => '909', 'name' => 'Huyện An Minh', 'region_id' => '91'],
            ['id' => '910', 'name' => 'Huyện Vĩnh Thuận', 'region_id' => '91'],
            ['id' => '911', 'name' => 'Huyện Phú Quốc', 'region_id' => '91'],
            ['id' => '912', 'name' => 'Huyện Kiên Hải', 'region_id' => '91'],
            ['id' => '913', 'name' => 'Huyện U Minh Thượng', 'region_id' => '91'],
            ['id' => '914', 'name' => 'Huyện Giang Thành', 'region_id' => '91'],
            ['id' => '916', 'name' => 'Quận Ninh Kiều', 'region_id' => '92'],
            ['id' => '917', 'name' => 'Quận Ô Môn', 'region_id' => '92'],
            ['id' => '918', 'name' => 'Quận Bình Thuỷ', 'region_id' => '92'],
            ['id' => '919', 'name' => 'Quận Cái Răng', 'region_id' => '92'],
            ['id' => '923', 'name' => 'Quận Thốt Nốt', 'region_id' => '92'],
            ['id' => '924', 'name' => 'Huyện Vĩnh Thạnh', 'region_id' => '92'],
            ['id' => '925', 'name' => 'Huyện Cờ Đỏ', 'region_id' => '92'],
            ['id' => '926', 'name' => 'Huyện Phong Điền', 'region_id' => '92'],
            ['id' => '927', 'name' => 'Huyện Thới Lai', 'region_id' => '92'],
            ['id' => '930', 'name' => 'Thành phố Vị Thanh', 'region_id' => '93'],
            ['id' => '931', 'name' => 'Thị xã Ngã Bảy', 'region_id' => '93'],
            ['id' => '932', 'name' => 'Huyện Châu Thành A', 'region_id' => '93'],
            ['id' => '933', 'name' => 'Huyện Châu Thành', 'region_id' => '93'],
            ['id' => '934', 'name' => 'Huyện Phụng Hiệp', 'region_id' => '93'],
            ['id' => '935', 'name' => 'Huyện Vị Thuỷ', 'region_id' => '93'],
            ['id' => '936', 'name' => 'Huyện Long Mỹ', 'region_id' => '93'],
            ['id' => '937', 'name' => 'Thị xã Long Mỹ', 'region_id' => '93'],
            ['id' => '941', 'name' => 'Thành phố Sóc Trăng', 'region_id' => '94'],
            ['id' => '942', 'name' => 'Huyện Châu Thành', 'region_id' => '94'],
            ['id' => '943', 'name' => 'Huyện Kế Sách', 'region_id' => '94'],
            ['id' => '944', 'name' => 'Huyện Mỹ Tú', 'region_id' => '94'],
            ['id' => '945', 'name' => 'Huyện Cù Lao Dung', 'region_id' => '94'],
            ['id' => '946', 'name' => 'Huyện Long Phú', 'region_id' => '94'],
            ['id' => '947', 'name' => 'Huyện Mỹ Xuyên', 'region_id' => '94'],
            ['id' => '948', 'name' => 'Thị xã Ngã Năm', 'region_id' => '94'],
            ['id' => '949', 'name' => 'Huyện Thạnh Trị', 'region_id' => '94'],
            ['id' => '950', 'name' => 'Thị xã Vĩnh Châu', 'region_id' => '94'],
            ['id' => '951', 'name' => 'Huyện Trần Đề', 'region_id' => '94'],
            ['id' => '954', 'name' => 'Thành phố Bạc Liêu', 'region_id' => '95'],
            ['id' => '956', 'name' => 'Huyện Hồng Dân', 'region_id' => '95'],
            ['id' => '957', 'name' => 'Huyện Phước Long', 'region_id' => '95'],
            ['id' => '958', 'name' => 'Huyện Vĩnh Lợi', 'region_id' => '95'],
            ['id' => '959', 'name' => 'Thị xã Giá Rai', 'region_id' => '95'],
            ['id' => '960', 'name' => 'Huyện Đông Hải', 'region_id' => '95'],
            ['id' => '961', 'name' => 'Huyện Hoà Bình', 'region_id' => '95'],
            ['id' => '964', 'name' => 'Thành phố Cà Mau', 'region_id' => '96'],
            ['id' => '966', 'name' => 'Huyện U Minh', 'region_id' => '96'],
            ['id' => '967', 'name' => 'Huyện Thới Bình', 'region_id' => '96'],
            ['id' => '968', 'name' => 'Huyện Trần Văn Thời', 'region_id' => '96'],
            ['id' => '969', 'name' => 'Huyện Cái Nước', 'region_id' => '96'],
            ['id' => '970', 'name' => 'Huyện Đầm Dơi', 'region_id' => '96'],
            ['id' => '971', 'name' => 'Huyện Năm Căn', 'region_id' => '96'],
            ['id' => '972', 'name' => 'Huyện Phú Tân', 'region_id' => '96'],
            ['id' => '973', 'name' => 'Huyện Ngọc Hiển', 'region_id' => '96']
        ];

        DB::table('cities')->insert($cities);
    }
}
